"""World model (Predictor)."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/02i_models.worldmodel.predictor.ipynb.

# %% auto 0
__all__ = ['WorldModel', 'RewardModel']

# %% ../../../nbs/02i_models.worldmodel.predictor.ipynb 3
from fastcore import *
from fastcore.utils import *

# %% ../../../nbs/02i_models.worldmodel.predictor.ipynb 4
import torch
import torch.nn as nn
from ..dense import DenseModel


# %% ../../../nbs/02i_models.worldmodel.predictor.ipynb 5
from ..dense import DenseModel
class WorldModel(nn.Module):
    def __init__(
        self,
        obs_dim: int,
        msg_dim: int,
        action_dim: int,
        output_dim: int,
        model_info:dict={'layers': 3,'node_size': 128,'activation': nn.ReLU,'dist': None}
    ):
        super().__init__()

        self.message_proj = nn.Linear(msg_dim, model_info['node_size'], bias=True) #[B, D]
        self.action_proj = nn.Linear(action_dim, model_info['node_size'], bias=True) # [B, D]
        self.obs_proj = nn.Linear(obs_dim, model_info['node_size'], bias=True) # [B, D]

        self.fuse = nn.Linear(model_info['node_size'] * 3, model_info['node_size'])
        self.wm = DenseModel(output_shape= (output_dim,), input_size=model_info['node_size'], info= model_info)

    def forward(self, z, action, msg):
        msg = self.message_proj(msg)
        act = self.action_proj(action)
        z = self.obs_proj(z)

        out = self.fuse(torch.cat([z, act, msg], dim= -1))
        out = self.wm(out)
        return out


# %% ../../../nbs/02i_models.worldmodel.predictor.ipynb 7
class RewardModel(nn.Module):
    def __init__(
        self,
        obs_dim: int,
        msg_dim: int,
        action_dim: int,
        output_dim: int,
        model_info:dict= {'layers': 3,'node_size': 128,'activation': nn.ReLU,'dist': None}
    ):
        super().__init__()

        self.message_proj = nn.Linear(msg_dim, model_info['node_size'], bias=True) #[B, D]
        self.action_proj = nn.Linear(action_dim, model_info['node_size'], bias=True) # [B, D]
        self.obs_proj = nn.Linear(obs_dim, model_info['node_size'], bias=True) # [B, D]

        self.fuse = nn.Linear(model_info['node_size'] * 3, model_info['node_size']) # [B, D]
        self.rm = DenseModel(output_shape= (output_dim,), input_size=model_info['node_size'], info= model_info) # [B, 1]

    def forward(self, z, action, msg):
        msg = self.message_proj(msg)
        act = self.action_proj(action)
        z = self.obs_proj(z)

        out = self.fuse(torch.cat([z, act, msg], dim= -1))
        out = self.rm(out)
        return out
