"""This module implements LeJepa training procedure with three predictors and two input modalities."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/05b_trainers.findgoal_trainer.ipynb.

# %% auto 0
__all__ = ['CHECKPOINT_FREQ', 'WMTrainer']

# %% ../../nbs/05b_trainers.findgoal_trainer.ipynb 3
from fastcore import *
from fastcore.utils import *
from torchvision.utils import save_image
import torch
import os
from torch import nn
import pandas as pd

# %% ../../nbs/05b_trainers.findgoal_trainer.ipynb 5
from ..models.utils import save_checkpoint
from ..loggers.base import AverageMeter
from ..losses.sigreg import SIGReg, SIGRegDistributed
from ..models.utils import flatten_conv_output
from einops import rearrange

class WMTrainer:
    def __init__(self, cfg, model, train_loader, sampler,
                 optimizer=None, device=None,earlystopping=None, 
                 scheduler=None, writer= None, verbose= None, logger= None):
        
        self.cfg = cfg
        self.device = device

        self.train_loader = train_loader
        self.sampler = sampler

        self.model = model['jepa']
        self.msg_enc = model['msg_enc']
        self.comm_module = model['comm_module']
        self.proj = model['proj']

        self.optimizer = optimizer
        self.earlystopping = earlystopping
        self.scheduler = scheduler

        self.writer = writer
        self.verbose = verbose
        self.logger = logger

        self.sigreg = SIGReg().to(self.device)
        self.disSigReg = SIGRegDistributed().to(self.device)
        self.cross_entropy = nn.CrossEntropyLoss()

        self.lambda_ = self.cfg.loss.lambda_
        self.W_H_PRED = self.cfg.loss.W_H_PRED
        self.W_SIM_T = self.cfg.loss.W_SIM_T

        self.agents = [f"agent_{i}" for i in range(len(self.cfg.env.agents))]

        self.dmpc_dir = os.path.join(self.cfg.log_dir, 'dmpc_marlrid', self.cfg.now)
        if not os.path.exists(self.dmpc_dir):
            os.makedirs(self.dmpc_dir , exist_ok=True)

    

# %% ../../nbs/05b_trainers.findgoal_trainer.ipynb 8
@patch
def criterion(self: WMTrainer, global_step, Z0, Z, msg_target, msg_hat, proj_h, proj_z, mask_t, mask):

    flat_encodings = flatten_conv_output(Z0) # [T, B, c`, h`, w`] => [T, B, d]
    sigreg_img = self.disSigReg(flat_encodings[:1], global_step= global_step)

    transition_mask = mask_t[1:] * mask_t[:-1]
    diff = (Z0[1:] - Z[1:]).pow(2).mean(dim=(2, 3, 4)) # (T-1, B)
    sim_loss = (diff * transition_mask).sum() / transition_mask.sum().clamp_min(1)

    if self.cfg.loss.vicreg.sim_coeff_t:
        diff_t = ( Z0[1:] -  Z0[:-1]).pow(2).mean(dim=(2, 3, 4))# (T-1, B)
        sim_loss_t = (diff_t * transition_mask).sum() / transition_mask.sum().clamp_min(1)
    else:
        sim_loss_t = torch.zeros([1], device=self.device)

    msg_pred_loss = self.cross_entropy(msg_hat, msg_target)

    sigreg_msg = self.disSigReg(proj_h, global_step= global_step)
    sigreg_obs = self.disSigReg(proj_z, global_step= global_step)

    inv_loss_sender = (proj_z - proj_h).square().mean(dim= -1)  # [T, B, d= 128] => [T, B]
    inv_loss_sender = (inv_loss_sender * mask).sum() / mask.sum().clamp_min(1) 

    return {
        'sigreg_img': sigreg_img,
        'sigreg_msg': sigreg_msg,
        'sigreg_obs': sigreg_obs,
        'sim_loss_dynamics': sim_loss,
        'sim_loss_t': sim_loss_t,
        'inv_loss_sender': inv_loss_sender,
        'msg_pred_loss': msg_pred_loss
    }
            

# %% ../../nbs/05b_trainers.findgoal_trainer.ipynb 9
from ..models.utils import flatten_conv_output
from einops import rearrange
@patch
def train_epoch(self: WMTrainer, epoch):
    self.model.train()
    
    total_running_loss = 0.0
    total_valid_steps = 0

    self.logger.info(f"Device used: {self.device}")
    self.sampler.set_epoch(epoch)
    for batch_idx, data in enumerate(self.train_loader):
        global_step = epoch * len(self.train_loader) + batch_idx
        self.optimizer.zero_grad()
        batch_loss = 0

        for agent_id in self.agents:
            obs, pos, _, _, act, _, dones = data[agent_id].values()
            mask = (~dones.bool()).float().to(self.device) # [B, T, d=1]
            mask = rearrange(mask, 'b t d-> b (t d)', d=1)
            mask_t = rearrange(mask, 'b t -> t b')
            
            agent_loss = 0

            if mask.sum() == 0:
                continue 

            obs = obs.to(self.device)
            pos = pos.to(self.device)
            act = act.to(self.device)

            self.logger.info(f"device used for main agent data: {mask_t.device} {obs.device}, {act.device}")

            for other_agent in self.agents:
                if other_agent != agent_id:
                    obs_sender, pos_sender, msg, msg_target, _,_, _ = data[other_agent].values()

                    obs_sender = obs_sender.to(self.device)
                    pos_sender = pos_sender.to(self.device)
                    msg = msg.to(self.device)
                    msg_target = msg_target.to(self.device)
                    self.logger.info(f"device used for other agent data: {obs_sender.device}, {msg.device}")
            
            h = self.msg_enc(msg) # [B, T, C, H, W] => [B, T, dim=32]

            Z0, Z = self.model(x= obs, pos= pos, actions= act, msgs= h, T= act.size(1)-1)#[B, T, c, h, w] =>  [T, B, c, h, w]
            
            if hasattr(self.model, 'module'):
                z_sender = self.model.module.backbone(obs_sender, position = pos_sender)  #[B, T, c, h, w] => [B, T, c`, h`, w`]
            else:
                z_sender = self.model.backbone(obs_sender, position = pos_sender)  #[B, T, c, h, w] => [B, T, c`, h`, w`]
                
            proj_z, proj_h = self.proj(z_sender, h) #[B, T, c`, h`, w`],[B, T, dim=32] => [T, B, d= 128], [T, B, d= 128]
            msg_hat = self.comm_module(z_sender)  # [B, T, c`, h`, w`] => [B, T, C=5, H=7, W=7]
            
            losses = self.criterion(global_step, Z0, Z, msg_target, msg_hat, proj_h, proj_z, mask_t, mask)
          
            if self.verbose:
                self.writer.write({
                    f'{agent_id}/train/sigreg_img': losses['sigreg_img'].item(),
                    f'{agent_id}/train/sigreg_msg': losses['sigreg_msg'].item(),
                    f'{agent_id}/train/sigreg_obs': losses['sigreg_obs'].item(),
                    f'{agent_id}/train/sim_loss': losses['sim_loss_dynamics'].item(),
                    f'{agent_id}/train/sim_loss_t': losses['sim_loss_t'].item(),
                    f'{agent_id}/train/msg_pred_loss': losses['msg_pred_loss'].item(),
                    f'{agent_id}/train/inv_loss_sender': losses['inv_loss_sender'].item(),
                })
                
            self.logger.info("Losses: %s" % str({k: v.item() for k, v in losses.items()}))
            
            sender_jepa_loss = self.lambda_ * (losses['sigreg_obs'] + losses['sigreg_msg']) + (1 - self.lambda_) * losses['inv_loss_sender']
            rec_jepa_loss = (1 - self.lambda_) * losses['sim_loss_dynamics'] + self.lambda_ * losses['sigreg_img']
            comm_mod_loss = self.W_H_PRED * losses['msg_pred_loss']
            smothness_loss = self.W_SIM_T * losses['sim_loss_t']

            self.logger.info(f"JEPA Losses: sender_jepa_loss: {sender_jepa_loss.item():.4f}, rec_jepa_loss: {rec_jepa_loss.item():.4f}, sim_loss_t: {losses['sim_loss_t'].item():.4f}")

            agent_loss = sender_jepa_loss + rec_jepa_loss + smothness_loss + comm_mod_loss
            self.logger.info(f"Agent: {agent_id}, agent_loss: {agent_loss.item():.4f}")
            
            batch_loss += agent_loss

            num_valid = mask.sum().item()
            total_running_loss += agent_loss.item() * num_valid
            total_valid_steps += num_valid
            
        loss = batch_loss / len(self.agents)
        loss.backward()
        self.optimizer.step()

        if batch_idx % 20 == 0:
            self.logger.info(f'Train Epoch: {epoch} [{batch_idx * len(obs)}/{len(self.train_loader.dataset)} '
                  f'({100. * batch_idx / len(self.train_loader):.0f}%)]\tLoss: {loss.item():.6f}')

    final_epoch_loss = (total_running_loss / total_valid_steps) / len(self.agents)
    self.logger.info(f'====> Epoch: {epoch} Average loss: {final_epoch_loss:.4f}')

    return final_epoch_loss
       

# %% ../../nbs/05b_trainers.findgoal_trainer.ipynb 10
import wandb
CHECKPOINT_FREQ = 1
@patch
def fit(self: WMTrainer):

    latest_file = "latest.pt"
    folder = self.dmpc_dir
    latest_path = os.path.join(folder, latest_file)
    
    loss_meter = AverageMeter()
    lst_dfs = []

    for epoch in range(1, self.cfg.epochs + 1):
        self.logger.info("Epoch %d" % (epoch))
        lr = self.scheduler.adjust_learning_rate(epoch)
        train_loss = self.train_epoch(epoch)
        loss_meter.update(train_loss)
        
        def save_checkpoint(epoch, path):
            if not self.verbose:
                return
            
            def get_state(m):
                return m.module.state_dict() if hasattr(m, 'module') else m.state_dict()
            
            save_dict = {
                'epoch': epoch,
                'jepa': get_state(self.model),
                'msg_enc': get_state(self.msg_enc),
                'comm_module': get_state(self.comm_module),
                'proj': get_state(self.proj),
                'train_loss': train_loss,
                'optimizer': self.optimizer.state_dict(),
                "lr": lr,
            }
            try:
                torch.save(save_dict, path)
                self.logger.info(f"Successfully saved checkpoint to {path}")
            except Exception as e:
                self.logger.info(f"Encountered exception when saving checkpoint: {e}")
        
        self.logger.info("avg. loss %.3f" % loss_meter.avg)

        df = pd.DataFrame.from_records([{"epoch": epoch ,"train_loss": train_loss}], index= "epoch")
        lst_dfs.append(df)

        if epoch % CHECKPOINT_FREQ == 0 or epoch == (self.cfg.epochs - 1):
            save_checkpoint(epoch + 1, latest_path)
            if self.cfg.save_every_freq > 0 and epoch % self.cfg.save_every_freq == 0:
                save_every_file = f"e{epoch}.pt"
                save_every_path = os.path.join(folder, save_every_file)
                save_checkpoint(epoch + 1, save_every_path)

        to_log = {
            "train_loss": train_loss, 
        }

        if self.verbose:
            self.writer.write(to_log)

    df_res = pd.concat(lst_dfs)
    df_reset = df_res.reset_index()
    if self.verbose:
        self.writer.write({'Train Loss Table': wandb.Table(dataframe= df_reset)})

    self.writer.finish()
    return df_reset
