"""This module implements LeJepa training procedure with three predictors and two input modalities."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/05a_trainers.utils.ipynb.

# %% auto 0
__all__ = ['get_cls', 'init_trainer']

# %% ../../nbs/05a_trainers.utils.ipynb 3
from fastcore import *
from fastcore.utils import *
from torchvision.utils import save_image
import torch
import os
from torch import nn
import pandas as pd

# %% ../../nbs/05a_trainers.utils.ipynb 4
import importlib
def get_cls(module_name, class_name):
    module = importlib.import_module(module_name)
    return getattr(module, class_name)


# %% ../../nbs/05a_trainers.utils.ipynb 5
def init_trainer(cfg, model, train_loader, sampler, optimizer,
                device, scheduler, writer, verbose, logger, 
                earlystopping= None):
    
    WMTrainer = get_cls(f"mawm.trainers.{cfg.trainer.class_name}", "WMTrainer")
    trainer = WMTrainer(cfg, model, train_loader, sampler = sampler, optimizer= optimizer,
                        device= device, earlystopping= earlystopping, scheduler= scheduler,
                        writer= writer, verbose= verbose, logger = logger)
    return trainer
