"""This module handles all aspects of the world model, including state representation, environment dynamics, and prediction."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/05c_trainers_world_model_trainer.ipynb.

# %% auto 0
__all__ = ['WMTrainer']

# %% ../../nbs/05c_trainers_world_model_trainer.ipynb 3
from fastcore import *
from fastcore.utils import *
import torch

# %% ../../nbs/05c_trainers_world_model_trainer.ipynb 4
class WMTrainer:
    """ Base Trainer class """
    def __init__(self, cfg):
        self.cfg = cfg
        
