"""Contain various loss functions used for optimization."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/03a_losses.custom_loss.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/03a_losses.custom_loss.ipynb 3
from fastcore import *
from fastcore.utils import *

# %% ../../nbs/03a_losses.custom_loss.ipynb 4
import torch
import torch.nn as nn
import torch.nn.functional as F

# %% ../../nbs/03a_losses.custom_loss.ipynb 5
def _reward_loss(reward_dist, rewards):
    reward_loss = -torch.mean(reward_dist.log_prob(rewards))
    return reward_loss

# %% ../../nbs/03a_losses.custom_loss.ipynb 6
def _vae_loss(recon_x, x, mu, logsigma):
    """ VAE loss function """
    BCE = F.mse_loss(recon_x, x, reduction='sum')
    KLD = -0.5 * torch.sum(1 + 2 * logsigma - mu.pow(2) - (2 * logsigma).exp())
    return BCE + KLD

# %% ../../nbs/03a_losses.custom_loss.ipynb 7
def _l1_loss(z, h, loss_exp=1.0):
    return torch.mean(torch.abs(z - h) ** loss_exp) / loss_exp
