"""Acts as module \__init__ for MarlGrid envs creation"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../../../nbs/07k_envs.marlgrid_environments.ipynb.

# %% ../../../../../nbs/07k_envs.marlgrid_environments.ipynb 3
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
from fastcore import *
from fastcore.utils import *

# %% auto 0
__all__ = ['make_environment']

# %% ../../../../../nbs/07k_envs.marlgrid_environments.ipynb 4
import numpy as np
import gymnasium as  gym
from MAWM.envs.marl_grid.envs.findgoal_env .grid_world_environment import create_grid_world_env
from MAWM.envs.marl_grid.envs.findgoal_env.find_goal_wrapper import DictObservationNormalizationWrapper, \
    GridWorldEvaluatorWrapper


# %% ../../../../../nbs/07k_envs.marlgrid_environments.ipynb 5
def make_environment(env_cfg, lock=None):
    """ Use this to make Environments """

    env_name = env_cfg.env_name

    assert env_name.startswith('MarlGrid')
    # import pdb; pdb.set_trace()
    env = create_grid_world_env(env_cfg)
    # env = GridWorldEvaluatorWrapper(env)
    # env = DictObservationNormalizationWrapper(env)

    return env

