"""This module handles all communication-related functionalities, including message passing, event handling, and notifications."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01d_data.enums.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/01d_data.enums.ipynb 3
from fastcore import *
from fastcore.utils import *
