# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01a_data.generate_data.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/01a_data.generate_data.ipynb 3
from fastcore import *
from fastcore.utils import *
