"""This module handles all communication-related functionalities, including message passing, event handling, and notifications."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01b_data_utils.ipynb.

# %% auto 0
__all__ = ['ASIZE', 'LSIZE', 'RSIZE', 'RED_SIZE', 'SIZE', 'transform_train', 'transform_test']

# %% ../../nbs/01b_data_utils.ipynb 3
from fastcore import *
from fastcore.utils import *

# %% ../../nbs/01b_data_utils.ipynb 4
import math
from os.path import join, exists
import torch
from torchvision import transforms
import numpy as np

ASIZE, LSIZE, RSIZE, RED_SIZE, SIZE =\
    3, 32, 256, 32, 40

transform_train = transforms.Compose([
    transforms.ToPILImage(),
    transforms.Resize((RED_SIZE, RED_SIZE)),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
])

transform_test = transforms.Compose([
    transforms.ToPILImage(),
    transforms.Resize((RED_SIZE, RED_SIZE)),
    transforms.ToTensor(),
])

