project_name: vae_marlrid

epochs: 1000
loss_fn: CrossEntropyLoss
writer: WandbWriter
noreload: False

# save and log directories
root_dir: /scratch/project_2009050/
save_dir : models
res_dir: results
log_dir: ../logs
state_dir: aggregated_model_


data:
  data_dir: /scratch/project_2009050/datasets/marl_grid/marl_grid_data
  batch_size: 32
  name: marlrid


model:
  name: VAE
  channels: 3
  img_size: 32
  latent_size: 32
  grad_norm_clip: 1.0


optimizer:
  name: Adam
  lr: 0.0001