project_name: lejepa_marlgrid

epochs: 300
loss_fn: CrossEntropyLoss
writer: WandbWriter
noreload: False
lambda_: 0.05

# save and log directories
root_dir: /scratch/project_2009050/
save_dir : models
res_dir: results
log_dir: ../logs
state_dir: aggregated_model_

env:
  agents: ['agent_0', 'agent_1']

data:
  data_dir: /scratch/project_2009050/datasets/marl_grid/marl_grid_data
  batch_size: 32
  buffer_size: 10
  V: 2
  obs_key: pov
  name: marlrid


model:
  name: encoder
  channels: 3
  img_size: 42
  latent_size: 42
  grad_norm_clip: 1.0


optimizer:
  name: Adam
  lr: 0.0001