project_name: Debug-3
  
epochs: 600
save_every_freq: 10
loss_fn: CrossEntropyLoss
writer: WandbWriter
noreload: False
lambda_: 0.02

root_dir: /scratch/project_2009050/
save_dir : models
res_dir: results
log_dir: ./logs
log_subdir: mawm_ds_200k
env:
  agents: ['agent_0', 'agent_1']

data:
  data_dir: /scratch/project_2009050/datasets/MarlGridV3/ #/home/sehadn1/MarlGridV3
  batch_size: 128  
  seq_len: 40
  data_size: 200000
  V: 4
  obs_key: pov
  name: marlgrid-findgoal
  loader:
    num_workers: 0
    pin_memory: true
    drop_last: true
    shuffle: true
    persistent_workers: false


model:
  name: JEPA
  channels: 3
  img_size: 42
  backbone:
    arch: MeNet6
    backbone_subclass: d4rl_a
    backbone_mlp: null
    backbone_width_factor: 2
    input_dim: 4
    channels: 3
    position_dim: 2
    position_encoder_arch: "2-8-16"
  predictor:
    action_dim: 5
    residual: true
    action_encoder_arch: "5-32-64-32" #'id'
    arch: ConvPredictor
    predictor_subclass: d4rl_b_p
    rnn_converter_arch: ''
    rnn_layers: 1
    rnn_state_dim: 512
    z_dim: 0
    z_min_std: 0.1


loss:
  projector: id
  sigreg:
    msg: 0.05
    img: 4.0
    time: 3.0
  inv_loss:
    coeff: 0.95
  msg_pred:
    coeff: 1.0
  alpha: 4.0
  beta: 6.9
  gamma: 0.75
  omega: 5.4
  lambd: 3.0
  idm:
    action_dim: 5
    coeff: 0.2
    arch: 'conv'
    use_pred: false
    arch_subclass: a
  vicreg:
    projector: id
    random_projector: false
    sim_coeff: 1.0
    std_coeff: 3
    cov_coeff: 6.9238
    std_coeff_t: 0.24535
    cov_coeff_t: 0.0
    sim_coeff_t: 0.74242
    cov_per_feature: false
    adjust_cov: true
    cov_chunk_size: null
    std_margin: 1.0
    std_margin_t: 1.0

  prediction_propio:
    global_coeff: 1.4108



optimizer:
  name: Adam
  lr: 0.001
  weight_decay: 0.0001 
  scheduler:
    name: cosine
    T_max: 500
    eta_min: 1e-05

trainer:
  class_name: findgoal_trainer