"""Build predictors from base archs."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/02g_models.dynamics.ipynb.

# %% auto 0
__all__ = ['build_predictor']

# %% ../../../nbs/02g_models.dynamics.ipynb 3
from fastcore import *
from fastcore.utils import *

# %% ../../../nbs/02g_models.dynamics.ipynb 4
import torch
import torch.nn as nn

# %% ../../../nbs/02g_models.dynamics.ipynb 5
from typing import Optional, Union

import torch
from torch import nn
from torch.nn import functional as F
from torch.distributions.normal import Normal
import numpy as np

from ..misc import build_mlp
from ..utils import *
from .enums import PredictorConfig, PredictorOutput


# %% ../../../nbs/02g_models.dynamics.ipynb 6
from .predictor import MLPPredictor, ConvPredictor, RNNPredictor, RNNPredictorV2, RNNPredictorV3, RNNPredictorBurnin
def build_predictor(
    config: PredictorConfig,
    repr_dim: int,
    action_dim: int,
    pred_propio_dim: Union[int, tuple],
    pred_obs_dim: Union[int, tuple],
    backbone_ln: Optional[torch.nn.Module] = None,
):
    arch = config.predictor_arch
    predictor_subclass = config.predictor_subclass
    rnn_layers = config.rnn_layers
    prior_arch = config.prior_arch
    posterior_arch = config.posterior_arch
    z_dim = config.z_dim
    z_min_std = config.z_min_std
    z_discrete = config.z_discrete
    z_discrete_dists = config.z_discrete_dists
    z_discrete_dim = config.z_discrete_dim
    posterior_drop_p = config.posterior_drop_p
    predictor_ln = config.predictor_ln
    posterior_input_type = config.posterior_input_type
    posterior_input_dim = config.posterior_input_dim
    if arch == "mlp":
        predictor = MLPPredictor(
            config=config,
            repr_dim=repr_dim,
            action_dim=action_dim,
            pred_propio_dim=pred_propio_dim,
            pred_obs_dim=pred_obs_dim,
            backbone_ln=backbone_ln,
        )
    # elif arch == "conv":
    #     predictor = PixelPredictorConv(action_dim=action_dim)
    elif arch == "conv2":
        predictor = ConvPredictor(
            config=config,
            repr_dim=repr_dim,
            predictor_subclass=predictor_subclass,
            z_discrete=z_discrete,
            z_discrete_dists=z_discrete_dists,
            z_discrete_dim=z_discrete_dim,
            z_dim=z_dim,
            z_min_std=z_min_std,
            posterior_drop_p=posterior_drop_p,
            prior_arch=prior_arch,
            posterior_arch=posterior_arch,
            posterior_input_type=posterior_input_type,
            posterior_input_dim=posterior_input_dim,
            action_dim=action_dim,
            pred_propio_dim=pred_propio_dim,
            pred_obs_dim=pred_obs_dim,
        )
    elif arch == "rnn":
        predictor = RNNPredictor(
            hidden_size=repr_dim,
            num_layers=rnn_layers,
            action_dim=action_dim,
            z_dim=z_dim,
        )
    elif arch == "rnnV2":
        predictor = RNNPredictorV2(
            config=config,
            hidden_size=repr_dim,
            num_layers=rnn_layers,
            input_size=action_dim,
            z_dim=z_dim,
            z_min_std=z_min_std,
            posterior_drop_p=posterior_drop_p,
            predictor_ln=predictor_ln,
            prior_arch=prior_arch,
            posterior_arch=posterior_arch,
            posterior_input_type=posterior_input_type,
            posterior_input_dim=posterior_input_dim,
            pred_propio_dim=pred_propio_dim,
            pred_obs_dim=pred_obs_dim,
            backbone_ln=backbone_ln,
            action_dim=action_dim,
        )
    elif arch == "rnnV3":
        predictor = RNNPredictorV3(
            hidden_size=repr_dim,
            num_layers=rnn_layers,
            input_size=action_dim,
        )
    elif arch == "rnn_burnin":
        predictor = RNNPredictorBurnin(
            hidden_size=repr_dim,
            output_size=repr_dim,
            num_layers=rnn_layers,
            action_dim=action_dim,
            z_dim=z_dim,
        )
  
    return predictor
