"""This module handles all aspects of the world model, including state representation, environment dynamics, and prediction."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02g_models.ipynb.

# %% auto 0
__all__ = ['logger', 'init_models']

# %% ../../nbs/02g_models.ipynb 3
from fastcore import *
from fastcore.utils import *
import torch

# %% ../../nbs/02g_models.ipynb 4
from functools import reduce
from torch.nn.parallel import DistributedDataParallel
from .jepa import JEPA
from .comm import MSGEnc, CommModule
from .misc import JepaProjector
import logging

logging.basicConfig(stream=sys.stdout, level=logging.INFO)
logger = logging.getLogger()

def init_models(
    cfg,
    device,
    distributed= True
):
    model = {}
    total_params = {}
    for agent in cfg.env.agents:
        
        jepa = JEPA(cfg.model, 
                    input_dim=(cfg.model.channels, cfg.model.img_size, cfg.model.img_size),
                    action_dim= cfg.model.predictor.action_dim)
        
        msg_enc = MSGEnc(num_primitives= 5,
                         latent_dim = 32)       
        
        proj = JepaProjector(z_channels=32,
                             c_input_dim=msg_enc.latent_dim)

        jepa.to(device)
        msg_enc.to(device)
        proj.to(device)

        def count_parameters(model):
            return sum(p.numel() for p in model.parameters() if p.requires_grad)
        
        logger.info("Agent: %s", agent)
        logger.info("JEPA Parameters: %d", count_parameters(jepa))
        logger.info("MSgEncoder Parameters: %d", count_parameters(msg_enc))
        logger.info("Projector Parameters: %d", count_parameters(proj))
        logger.info("-"*50)
        total_params[agent] = count_parameters(jepa) + count_parameters(msg_enc) + count_parameters(proj)

        model[agent] = {}
        if distributed:
            model[agent]["jepa"] = DistributedDataParallel(jepa, device_ids = [device], find_unused_parameters=True)
            model[agent]["msg_enc"] = DistributedDataParallel(msg_enc, device_ids = [device], find_unused_parameters= True)
            model[agent]["proj"] = DistributedDataParallel(proj, device_ids = [device], find_unused_parameters= True)
        else:
            model[agent]["jepa"] = jepa
            model[agent]["msg_enc"] = msg_enc
            model[agent]["proj"] = proj

    model['shared'] = {}
    comm_module = CommModule(input_channel= 32, num_primitives= 5)
    comm_module.to(device)
    logger.info("CommModule Parameters: %d", count_parameters(comm_module))

    logger.info("Total Parameters: %d", sum(total_params.values()) + count_parameters(comm_module))
    logger.info("Parameters per Agent: %s", total_params[cfg.env.agents[0]])

    if distributed:
        model['shared']["comm_module"] = DistributedDataParallel(comm_module, device_ids = [device], find_unused_parameters=True)
    else:
        model['shared']['comm_module'] = comm_module
    
    return model
