"""This module handles all aspects of the world model, including state representation, environment dynamics, and prediction."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02g_models.ipynb.

# %% auto 0
__all__ = ['logger', 'init_models']

# %% ../../nbs/02g_models.ipynb 3
from fastcore import *
from fastcore.utils import *
import torch

# %% ../../nbs/02g_models.ipynb 4
from functools import reduce
from torch.nn.parallel import DistributedDataParallel
from .jepa import JEPA
from .comm import MSGEnc, CommModule
from .misc import JepaProjector
import logging

logging.basicConfig(stream=sys.stdout, level=logging.INFO)
logger = logging.getLogger()

def init_models(
    cfg,
    device,
    distributed= True
):
    
    jepa = JEPA(cfg.model, input_dim=(cfg.model.channels, cfg.model.img_size, cfg.model.img_size),
                action_dim= cfg.model.predictor.action_dim)
    
    msg_enc = MSGEnc(num_primitives= 5, latent_dim = 32)
    comm_module = CommModule(input_channel= jepa.backbone.repr_dim[0])
    
    prod = reduce(lambda x, y: x * y, jepa.backbone.repr_dim)
    proj = JepaProjector(z_input_dim=prod, c_input_dim=msg_enc.latent_dim)

    jepa.to(device)
    msg_enc.to(device)
    comm_module.to(device)
    proj.to(device)

    def count_parameters(model):
        return sum(p.numel() for p in model.parameters() if p.requires_grad)
    
    logger.info("JEPA Parameters: %d", count_parameters(jepa))
    logger.info("MSgEncoder Parameters: %d", count_parameters(msg_enc))
    logger.info("CommModule Parameters: %d", count_parameters(comm_module))
    logger.info("Projector Parameters: %d", count_parameters(proj))
    total_params = count_parameters(jepa) + count_parameters(msg_enc) + count_parameters(comm_module) + count_parameters(proj)
    logger.info("Total Parameters: %d", total_params)

    if distributed:
        jepa = DistributedDataParallel(jepa, device_ids = [device], find_unused_parameters=True)
        msg_enc = DistributedDataParallel(msg_enc, device_ids = [device], find_unused_parameters= True)
        comm_module = DistributedDataParallel(comm_module, device_ids = [device], find_unused_parameters=True)
        proj = DistributedDataParallel(proj, device_ids = [device], find_unused_parameters= True)

    
    return jepa, msg_enc, comm_module, proj
