"""Model architecture that handles communicaion."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02b_models_comm.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../../nbs/02b_models_comm.ipynb 3
from fastcore import *
from fastcore.utils import *

# %% ../../nbs/02b_models_comm.ipynb 4
def foo(): pass
