"""This module handles all aspects of the world model, including state representation, environment dynamics, and prediction."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02j_models.utils.ipynb.

# %% auto 0
__all__ = ['save_checkpoint']

# %% ../../nbs/02j_models.utils.ipynb 3
from fastcore import *
from fastcore.utils import *
import torch

# %% ../../nbs/02j_models.utils.ipynb 4
def save_checkpoint(state, is_best, filename, best_filename):
    """ Save state in filename. Also save in best_filename if is_best. """
    torch.save(state, filename)
    if is_best:
        torch.save(state, best_filename)

