"""World model (Predictor)."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02c_models_world_model.ipynb.

# %% auto 0
__all__ = ['MLPPredictor']

# %% ../../nbs/02c_models_world_model.ipynb 3
from fastcore import *
from fastcore.utils import *

# %% ../../nbs/02c_models_world_model.ipynb 4
import torch
import torch.nn as nn

# %% ../../nbs/02c_models_world_model.ipynb 5
class MLPPredictor(nn.Module):
    def __init__(self, latent_dim=32, action_dim=1):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(latent_dim + action_dim, 128),
            nn.ReLU(),
            nn.Linear(128, latent_dim)
        )

    def forward(self, z, a):
        return self.net(torch.cat([z, a], dim=-1))

