"""World model (Predictor)."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02c_models_world_model.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../../nbs/02c_models_world_model.ipynb 3
from fastcore import *
from fastcore.utils import *

# %% ../../nbs/02c_models_world_model.ipynb 4
def foo(): pass
