"""Writer for logging to Weights and Biases (wandb) during training."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/06_wandb_writer.ipynb.

# %% auto 0
__all__ = ['WandbWriter']

# %% ../../nbs/06_wandb_writer.ipynb 3
from fastcore.utils import *
import pandas as pd
import wandb
import os
import argparse
import numpy as np

# %% ../../nbs/06_wandb_writer.ipynb 4
class WandbWriter:

    def __init__(self, cfg):
        self.cfg = argparse.Namespace(**cfg)
        self.exp_name = self.cfg.project_name + self.cfg.now
        key = os.getenv("WANDB_API_KEY")
        wandb.login(key=key, verify=False)
        self.run = wandb.init(project=self.cfg.project_name, name= self.exp_name, config=self.cfg)
        

# %% ../../nbs/06_wandb_writer.ipynb 5
@patch
def write(self: WandbWriter, log_dict):
    wandb.log(log_dict)

# %% ../../nbs/06_wandb_writer.ipynb 7
@patch
def finish(self: WandbWriter):
    self.run.finish()
