"""Determinstic program creator from a visual observation."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/03_program.creator.ipynb.

# %% auto 0
__all__ = ['SEQ_LEN', 'PAD_PRIM', 'PAD_PARAM', 'MAX_PARAMS', 'get_graphics_primitives', 'show_grid', 'get_cell_color',
           'get_grid_chars', 'create_specs_from_image', 'program_to_indices', 'batchify_programs']

# %% ../../nbs/03_program.creator.ipynb 3
from fastcore import *
from fastcore.utils import *

# %% ../../nbs/03_program.creator.ipynb 6
import cv2
import numpy as np
def get_graphics_primitives(img_np):
    img = cv2.cvtColor(img_np, cv2.COLOR_RGB2BGR)
    pixels = img.reshape(-1, 3)
    colors = np.unique(pixels, axis=0)

    primitives = []
    background_color = np.array([0, 0, 0])  # assuming black background
    for color in colors:
        if np.all(color == background_color):
            continue

        mask = cv2.inRange(img, color, color)
        contours, _ = cv2.findContours(
            mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE
        )

        for cnt in contours:
            x, y, w, h = cv2.boundingRect(cnt)
            primitives.append((color, x, y, w, h))
            
    return primitives
    


# %% ../../nbs/03_program.creator.ipynb 10
import cv2
import matplotlib.pyplot as plt
def show_grid(img, GRID = 7, CELL = 6):
    if not CELL:
        CELL = img.shape[0] // GRID
    
    vis = img.copy()
    vis = cv2.cvtColor(vis, cv2.COLOR_BGR2RGB)
    for i in range(1, GRID):
        cv2.line(vis, (i*CELL, 0), (i*CELL, 42), (255,255,255), 1)
        cv2.line(vis, (0, i*CELL), (42, i*CELL), (255,255,255), 1)
    plt.imshow(vis, interpolation="nearest")
    plt.axis("off")

    return vis
# show_grid(inp)

# %% ../../nbs/03_program.creator.ipynb 11
def get_cell_color(cell):
    np_to_tuple = lambda arr: tuple(int(x) for x in arr)
    pixels = cell.reshape(-1, 3)
    colors, counts = np.unique(pixels, axis=0, return_counts=True)
    # print(colors, len(colors), "+++++")
    # color = colors[np.argmax(counts)]
    if len(colors) == 1:
        if np_to_tuple(colors[0]) in [(0, 255, 0)]:
            return "G" #"Goal"
        elif np_to_tuple(colors[0]) in [(74, 65, 42)]:
            return "W" #"Wall"
        else:
            return "E" #"Empty"
        
    else:
        
        for color in colors:
            if np_to_tuple(color) in [(198, 0, 0), (28, 0, 0), (255, 0, 0)]:
                color = (255, 0, 0)
                return "R" #"RedAgent"
            elif np_to_tuple(color) in [(0, 0, 198), (0, 0, 255)]:
                color = (0, 0, 255)
                return "B" #"BlueAgent"
                
    

# %% ../../nbs/03_program.creator.ipynb 12
def get_grid_chars(img, GRID=7, CELL=6): 
    cells = [[cv2.cvtColor(img, cv2.COLOR_BGR2RGB)[j*CELL:(j+1)*CELL, i*CELL:(i+1)*CELL]
              for i in range(GRID)]
              for j in range(GRID)
            ]
    
    grid = np.zeros((GRID,GRID), dtype=object)
    for r in range(GRID):
        for c in range(GRID):
            color = get_cell_color(cells[r][c])
            grid[r][c] = color
    return grid

# %% ../../nbs/03_program.creator.ipynb 29
from ..core import *
def create_specs_from_image(
    img_np,
    GRID=7,
    CELL=6
):
    grid = get_grid_chars(img_np, GRID=GRID, CELL=CELL)
    
    wall_indices = np.argwhere(grid == "W")
    empty_indices = np.argwhere(grid == "E")
    goal_index = np.argwhere(grid == "G")
    blueagent_index = np.argwhere(grid == "B")
    redagent_index = np.argwhere(grid == "R")
    
    wall_prims  =[("CellObstacle", idx[0], idx[1]) for idx in wall_indices]
    wall_tokens = [(PRIM_NAME_TO_IDX[prim], [x, y]) for (prim, x, y) in wall_prims]
    
    empty_prims  =[("CellEmpty", idx[0], idx[1]) for idx in empty_indices]
    empty_tokens = [(PRIM_NAME_TO_IDX[prim], [x, y]) for (prim, x, y) in empty_prims]

    goal_index = (goal_index[0][0], goal_index[0][1]) if len(goal_index) > 0 else None
    blueagent_index = (blueagent_index[0][0], blueagent_index[0][1]) if len(blueagent_index) > 0 else None
    redagent_index = (redagent_index[0][0], redagent_index[0][1]) if len(redagent_index) > 0 else None

    program_tokens = wall_tokens + empty_tokens
    if goal_index:
        program_tokens += [(PRIM_NAME_TO_IDX["CellGoal"], [goal_index[0], goal_index[1]])]
        program_tokens += [(PRIM_NAME_TO_IDX["SeeGoal"])]

    if blueagent_index:
        program_tokens += [(PRIM_NAME_TO_IDX["CellAgent"], [blueagent_index[0], blueagent_index[1]])]

    if redagent_index:
        program_tokens += [(PRIM_NAME_TO_IDX["CellAgent"], [redagent_index[0], redagent_index[1]])]

    program = Program(tokens=program_tokens)
    
    return program

# %% ../../nbs/03_program.creator.ipynb 30
# program = create_specs_from_image(inp)

# %% ../../nbs/03_program.creator.ipynb 33
SEQ_LEN = 49
PAD_PRIM = len(PRIMITIVE_TEMPLATES)  # index for padding primitive
PAD_PARAM = -1  # value for padding parameters
MAX_PARAMS = 2  # maximum number of parameters per primitive
import torch
def program_to_indices(program):
    tokens = program.tokens[:SEQ_LEN]

    prims = [t[0] for t in tokens]
    params = [list(t[1])[:MAX_PARAMS] for t in tokens]

    # pad params
    for p in params:
        while len(p) < MAX_PARAMS:
            p.append(PAD_PARAM)

    # pad program length
    pad_len = SEQ_LEN - len(tokens)
    prims += [PAD_PRIM] * pad_len
    params += [[PAD_PARAM]*MAX_PARAMS for _ in range(pad_len)]

    return (
        torch.tensor(prims).unsqueeze(0),
        torch.tensor(params).unsqueeze(0)
    )

# %% ../../nbs/03_program.creator.ipynb 34
def batchify_programs(programs, seq_len=SEQ_LEN, max_params=MAX_PARAMS):
    prim_list = []
    param_list = []

    for p in programs:
        prim_ids, param_ids = program_to_indices(p)
        prim_list.append(prim_ids[0])       # (SEQ_LEN)
        param_list.append(param_ids[0])     # (SEQ_LEN, max_params)

    prim_batch = torch.stack(prim_list, dim=0)      # (B, SEQ_LEN)
    param_batch = torch.stack(param_list, dim=0)    # (B, SEQ_LEN, max_params)

    return prim_batch, param_batch

